namespace Cronus.Ordering.Models;

public class CartItem
{
    // Keys are generated by EF Core. Setting a key up front makes EF treat entities discovered
    // through a navigation (for example a new item on a tracked cart) as Modified, not Added.
    public Guid Id { get; set; }

    public Guid CartId { get; set; }

    public Cart? Cart { get; set; }

    public Guid MenuItemId { get; set; }

    public MenuItem? MenuItem { get; set; }

    public int Quantity { get; set; }

    /// <summary>Menu price captured when the item was added, so later price edits cannot change the cart.</summary>
    public decimal UnitPrice { get; set; }

    public decimal LineTotal => UnitPrice * Quantity;
}
